### PR TITLE
Map EmailStatusRepository, resolves Aerendir/aws-ses-monitor-bundle#26

### PR DESCRIPTION
**Pull request by jonny-no1**

### CODE REVIEW

**Comment by Aerendir** [comment]
I'm unsure if this will fix the issue. Anyway is a bug and it MUST be fixed, so I merged the PR.

Thank you!

**Comment by jonny-no1** [comment]
Thanks! The method `findOneBy*` is a magic method of doctrine's default repository. However, the standard implementation doesn't convert the email address to lowercase. Any email addresses that contain uppercase letters are therefore not found and when attempted to be added to the database in lowercase trigger the constraint violation.

**Comment by Aerendir** [comment]
Yes, you are right! I forgotten to add the repository to the mapping: I implemented the method but it was never used -.-'

Thank you for the fixing! :)

**Comment by jonny-no1** [comment]
Yep ;)

**Pull request merged**
